<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'kode_barang' => 273,
                'gambar_barang' => '["barang/0qR31bo3S2eWctZGW8syr8nK8UD75sOJBEyDZKRA.jpg","barang/xtUgfsDQPDQTnq60LeTXw9lZEXR5xct11P8DYoCk.webp","barang/fjzO2hIkIc3LEjKsiB1ff7ZsQvf9Z39mvOnQ7cwP.webp","barang/mQxv2LxTM8HTlp8ccI7elnlhiK8zYJfA9hGLdhF2.webp"]',
                'nama_barang' => 'Canon EOS 3000D Kit 18-55mm',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'DSLR Cam',
                'deskripsi_barang' => 'Kamera DSLR pemula yang sangat mudah digunakan, ramah baterai, cocok untuk tugas kuliah atau dokumentasi kasual.',
                'stok' => rand(1, 20),
                'harga_perhari' => 100000.00,
                'harga_perjam' => 4166.67,
                'catatan_kondisi_barang' => 'Fisik 90%, fungsi normal, lensa bebas jamur.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 274,
                'gambar_barang' => '["barang/ougn1UNB1TVb7Eu0vY8v37BpZFspfdBKDbVx5AV9.png","barang/le4NngNBxVtnIChRNyIplegoSdpwSUQUOviJiu5O.webp","barang/znkYFhSd4lf8x2FpcaYA6ptSdk9VeDOoxZpoOnMZ.webp","barang/TUZLBEyBcqGUkvgB3fzzelv1GP4LnKz0yHBlXxl8.webp"]',
                'nama_barang' => 'Canon EOS 850D (Body Only)',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'DSLR Cam',
                'deskripsi_barang' => 'DSLR kelas menengah dengan sistem autofokus cepat (45 titik silang), bagus untuk foto aksi atau olahraga.',
                'stok' => rand(1, 20),
                'harga_perhari' => 150000.00,
                'harga_perjam' => 6250.00,
                'catatan_kondisi_barang' => 'Karet grip rapat, sensor bersih, tombol responsif.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 275,
                'gambar_barang' => '["barang/cediabruOHWEPDUPfvdSweQdCNMNMFTEtIyC8Cwz.jpg","barang/jjWHsmZA58UknjBQohX2ZoYdKh9v4jJJECyOFZL9.jpg","barang/V7VoKhDkkRcL4xEfKLhkHmsVA07cYGqQpA1K9aSG.jpg","barang/Gii4OLr0jDRtNVpPFF0rOYNUTiaLK8KCg4MSjheP.jpg","barang/e4lWyI4aZz0RbrSgIdcviUdoL4lgIzVtP8PaanJ7.jpg"]',
                'nama_barang' => 'Nikon D7500 (Body Only)',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'DSLR Cam',
                'deskripsi_barang' => 'DSLR semi-profesional yang tangguh di segala cuaca (weather-sealed), sangat handal untuk dibawa hunting foto ke alam liar.',
                'stok' => rand(1, 20),
                'harga_perhari' => 180000.00,
                'harga_perjam' => 7500.00,
                'catatan_kondisi_barang' => 'Shutter count rendah, bodi kokoh, ada sedikit lecet pemakaian wajar.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 276,
                'gambar_barang' => '["barang/pDWrbgMpiKRwDfHGNxBIRGsNaJxW3LRdfNYQ0WHG.webp","barang/DEgJewMFuGdhEHS2wMl4txQnqDX6hH3fawYlbMtm.webp","barang/RcHmWwU1hONQuCOC0HmW23EnkyXAvZLmp1i6Ljpb.webp","barang/qDwpZpQLfA2gzUCUTG5IdZflQVkmVEMAkVOWIvlC.webp","barang/LVMDCsQQ8rDaXmi4wx9IWr6NKuV50ZjCsLBXMOAW.webp"]',
                'nama_barang' => 'Sony Alpha a6400 (Body Only)',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Mirrorless Cam',
                'deskripsi_barang' => 'Mirrorless APS-C paling populer untuk vlogger. Layar bisa ditekuk 180 derajat ke depan dan autofokusnya mengunci mata secara real-time.',
                'stok' => rand(1, 20),
                'harga_perhari' => 150000.00,
                'harga_perjam' => 6250.00,
                'catatan_kondisi_barang' => 'Sensor bersih, layar no-vignette, siap pakai.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 277,
                'gambar_barang' => '["barang/Fhh2keyCvRdB5WtTNwgUuX3eXcm4lzARZ80cETbO.webp","barang/sWePnmSnvC1Plpc9mCmXPgF3xr3TtBuW9LD2q6i7.webp","barang/lpU3zVyFhCg7p9s6xnWbiYE1AzWhj6l5sbkxB5dh.webp","barang/RreszgdRecc6Mc8SEWn7PAOFcIxqWJGPDsUs2UJO.webp","barang/cXhxBE8WG01eOLiv6pqSaawnTF3c9eEnZebGrqJQ.webp"]',
                'nama_barang' => 'Sony Alpha A7 III (Body Only)',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Mirrorless Cam',
                'deskripsi_barang' => 'Kamera Full-Frame standar industri rental. Sangat kuat untuk foto komersial, wedding, maupun video cinematic di kondisi minim cahaya.',
                'stok' => rand(1, 20),
                'harga_perhari' => 300000.00,
                'harga_perjam' => 12500.00,
                'catatan_kondisi_barang' => 'Karet jempol agak melar dikit, fungsi 100% normal, sensor bersih.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 278,
                'gambar_barang' => '["barang/ALXMnfmROblBpKAaqFdXtFQpx8aR82XJ8Lgx3Ivm.webp","barang/4uSQz3nR7tcDsYsjHDP8l5iI075CrsEm22KNSdpq.webp","barang/rwb65cBpcmB2LcacYQa2gMZxYGxCcXpTO41MfyaV.webp","barang/loZ5iWikjpP7FoYv9HgcmXfLHbD4pP9qbwToWKqQ.webp","barang/NfNVFR9dS0rWkSy5trhMvPbcSteyDISG5hepZcrq.webp"]',
                'nama_barang' => 'Fujifilm X-T30 II (Body Only)',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Mirrorless Cam',
                'deskripsi_barang' => 'Kamera mirrorless dengan desain retro yang estetik. Keunggulannya punya Film Simulation bawaan, jadi hasil foto tidak perlu diedit lagi.',
                'stok' => rand(1, 20),
                'harga_perhari' => 140000.00,
                'harga_perjam' => 5833.33,
                'catatan_kondisi_barang' => 'Mulus total, semua dial berfungsi dengan presisi.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 279,
                'gambar_barang' => '["barang/NGmyMRd9F3mcbccoTBbcchYvpnhZIxekUgJTe88m.webp","barang/HLdg4u0haRM6nA7opapf9lBThLzUsfFUkGyTG5iI.webp","barang/7uvsd7PxxJ191ylOckWBcFa4MuTQoZCDFx8kx1S6.webp","barang/owPYa3dNnVUFXGKiF0RFxFXfunHZXbOIWIY9SRxK.webp","barang/Q1Fpmp0gDqOc5rIdq4iz4PQuAnacT1SPF1nRMKcL.webp"]',
                'nama_barang' => 'Sony FX30 Cinema Line',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Video Cam',
                'deskripsi_barang' => 'Kamera berspesifikasi bioskop mini. Memiliki kipas internal jadi anti-overheat saat dipakai syuting seharian penuh.',
                'stok' => rand(1, 20),
                'harga_perhari' => 250000.00,
                'harga_perjam' => 10416.67,
                'catatan_kondisi_barang' => 'Lengkap dengan top handle, lubang ulir baut cage aman.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 280,
                'gambar_barang' => '["barang/rmVOf5yyK9q6ZNGUgiKPDHStxSuXRAwk1N9aYL0e.webp","barang/T1MvWL0L8SOjOPE0VrD2raqbFAIEYE7jAJCV5WKz.webp","barang/rZvQlVZOwAIPoXqKdl8On2ZWJLnsxxn1o0Ryx8Lw.webp","barang/FPO6T8vPDZaG4XT6ytUrpAw10XRcT4xxPjOpNa4O.webp","barang/4biD0je2h8hhNqfcviHkOsHuTlAY5HsY3GXLKdhh.webp"]',
                'nama_barang' => 'Panasonic Lumix GH5',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Video Cam',
                'deskripsi_barang' => 'Legenda kamera video indie dengan stabilizer bodi (IBIS) yang sangat tenang, sanggup merekam video 10-bit internal.',
                'stok' => rand(1, 20),
                'harga_perhari' => 160000.00,
                'harga_perjam' => 6666.67,
                'catatan_kondisi_barang' => 'Sensor aman, dual slot memori berfungsi normal.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 281,
                'gambar_barang' => '["barang/nLc4lRw6ornJY3LaJsJpBk4ecYNnrr6By1e2iQB6.png","barang/25ADx3FyN1taUI8Z0ukltThVLhEV96863mvkZFyu.jpg","barang/MVxZvXOT1CTsNZL6zvqwzyr5NJ63cRMBYXWaxuMv.jpg","barang/SnaWv4CunJ3S1ARa0Mr1sxqYt4AnmcVabx05dH8v.jpg"]',
                'nama_barang' => 'BMPCC 4K (Pocket Cinema)',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Video Cam',
                'deskripsi_barang' => 'Khusus untuk videografer profesional yang ingin hasil video mentah (RAW) dengan warna sinematik tingkat tinggi.',
                'stok' => rand(1, 20),
                'harga_perhari' => 280000.00,
                'harga_perjam' => 11666.67,
                'catatan_kondisi_barang' => 'Layar sentuh normal, baterai bawaan agak boros.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 282,
                'gambar_barang' => '["barang/yHqmMP7UxrKlNdkVH63Qp1iuOQFmTxNNmr3m7RWN.jpg","barang/Fy81Yz1C4SmH2JNLEkRhWvCRH55H6TklYHbIYmxN.jpg","barang/QhnmheATzcKCDfVOLtxmNyG7xUdBnVBEwnJlDg4j.jpg","barang/KJqrnM8ms7VykzOklFhwSWH9Xph5WDYBvr2Wmtub.jpg","barang/jENvzpDFXwcpHMwQLGxanj1TcfV2xMDCK1e7nxff.jpg"]',
                'nama_barang' => 'GoPro Hero 12 Black',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Action Cam',
                'deskripsi_barang' => 'Kamera aksi kasta tertinggi. Sangat cocok dipasangkan ke helm motovlog atau dibawa basah-basahan saat camping di air terjun.',
                'stok' => rand(1, 20),
                'harga_perhari' => 120000.00,
                'harga_perjam' => 5000.00,
                'catatan_kondisi_barang' => 'Lencana depan dipasang tempered glass, backdoor rapat anti air.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 283,
                'gambar_barang' => '["barang/EsEBIFSlrxdRnkffvFkz488wXxsy3cvtbpHIALk4.webp","barang/LcJ3Z2pucRPW4LuCrVwnr6Oq6OH7TwcUUe57l3Hx.webp","barang/gEgBew7d9k1CKt1joPmvhV7rb2pgsF3JGLxC0HnL.webp","barang/dN5jJI9ZGjkzo1YKPUCDJGQNfemL3SImrkQdMJRu.webp","barang/okV7CaVO4x0U4NXm4qNrbB4uq168pxZdHRQTFzAz.webp"]',
                'nama_barang' => 'DJI Osmo Action 4',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Action Cam',
                'deskripsi_barang' => 'Saingan berat GoPro dengan sensor lebih besar, sangat unggul untuk merekam aksi outdoor di sore atau malam hari.',
                'stok' => rand(1, 20),
                'harga_perhari' => 100000.00,
                'harga_perjam' => 4166.67,
                'catatan_kondisi_barang' => 'Mount magnetik kuat, bodi mulus.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 284,
                'gambar_barang' => '["barang/zDgt7yqD84GUxHZ41zideWGibvP8lzHcTTVhCHJt.webp","barang/vnWGFL6gY3Zv57dCmiDzFdl9Eeb4ZsCYTASSXgLT.webp","barang/DjGql7y7z1QTl6ZYMGMYKdrDuTsyk3tBjdojfyqz.webp","barang/EPkoYTjNNLCd1vAKTlx1b5IycLy5joU4Cjh74uGm.webp","barang/FxJedaUb26eWf58EoXjMaICMOccLD40aD5csOfcl.webp"]',
                'nama_barang' => 'Insta360 X3',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Action Cam',
                'deskripsi_barang' => 'Kamera aksi 360 derajat. Bisa merekam segala arah sekaligus, cocok untuk membuat konten kreatif tanpa pusing memikirkan arah kamera.',
                'stok' => rand(1, 20),
                'harga_perhari' => 130000.00,
                'harga_perjam' => 5416.67,
                'catatan_kondisi_barang' => 'Lensa cembung mulus tanpa baret (wajib pakai lens guard).',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 285,
                'gambar_barang' => '["barang/pYv8baqEDGNyuxmFPm0xqig4pornaT4OQ9RfZ8y2.webp","barang/sOHoilbLhNmDrTkt1ZHJB1lvb0ZolAl82L1trXML.webp","barang/YOHt0ehb9a3pOGmtzQfzq3rItY8BzEO0qTCl7ucu.webp","barang/TleeJFfedclHRSn4NSMAGc4zFTUNpg0hVtnaevP9.webp","barang/0oyldeRyvfM9bHGm1tV6bByyRSdsPBItcUCYjQUh.webp"]',
                'nama_barang' => 'Sigma 16mm f/1.4 DC DN (Sony E)',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lensa',
                'deskripsi_barang' => 'Lensa lebar premium. Sangat tajam, pas sekali dipasang ke Sony a6400 atau FX30 untuk vlogging jarak dekat atau foto pemandangan malam bintang.',
                'stok' => rand(1, 20),
                'harga_perhari' => 60000.00,
                'harga_perjam' => 2500.00,
                'catatan_kondisi_barang' => 'Optik bersih, no fog, no jamur.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 286,
                'gambar_barang' => '["barang/WdBTDym8fpZnMwg3uGhAbE1ykup1ZvAC9rKqjJS4.webp","barang/t4TkWlgUppwQJaSQqoNdkAopQOArZmUk52QrayMX.webp","barang/1Im42trKbPFvJbksraBsrsCJPLr6l9SJExPHWWJr.webp","barang/mLTfumYFPCftyuqlBEXxuglzAwtWwtYppKrfunGf.webp","barang/OYualZjBvPHJiVTT6RvZNro8tPIxprUDIozhEqIQ.webp"]',
                'nama_barang' => 'Sony FE 50mm f/1.8',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lensa',
                'deskripsi_barang' => 'Lensa potret esensial. Memberikan efek latar belakang blur (bokeh) yang sangat halus untuk memisahkan objek dengan objek di belakangnya.',
                'stok' => rand(1, 20),
                'harga_perhari' => 40000.00,
                'harga_perjam' => 1666.67,
                'catatan_kondisi_barang' => 'Fokus cepat, kelengkapan lensa + hood.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 287,
                'gambar_barang' => '["barang/491oiPVSc5ebn1oejYhAI0fakJv7snQyhczJkk33.webp","barang/pZAzxDOjFcITK9jEPOFMGavmqHqIi63LofKJieDw.webp","barang/IrJgS3ZzszHYgJ8yywAQOEpOG0L8yVBcwn7Ecz3S.webp","barang/d9AaRgKweQWwDfd88COWCV4Xa5sFiY9y72NdgksZ.webp","barang/LdkF5dZTw5EAfNswFtchR6b0CpxQAAJjRjGLfj4q.webp"]',
                'nama_barang' => 'Tamron 28-75mm f/2.8 G2 (Sony E)',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lensa',
                'deskripsi_barang' => 'Lensa zoom serbaguna bukaan konstan f/2.8. Ini adalah upgrade terbaik untuk menggantikan lensa bawaan (kit) bagi pengguna Sony A7 III.',
                'stok' => rand(1, 20),
                'harga_perhari' => 100000.00,
                'harga_perjam' => 4166.67,
                'catatan_kondisi_barang' => 'Karet kencang, fungsi zoom smooth.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 288,
                'gambar_barang' => '["barang/T3yVpNbDODy6BiJA40DUjUntuzcPp2X7eTwslpcq.webp","barang/2d89aWwh5nEHO0kdVDGGDwYWrzHgMEnmjELVoJB6.webp","barang/XI3FzlKkDC8fCQe9xKCTuIwhSfzmZHCcjzr3fWMY.webp","barang/HtJjPRFmbDTKdt3OgCrCMJuwEUMk0mBvT6u9FIVA.webp","barang/tRBWSTRcWUWPsXdIkEPPdhbtj0oeaiEK2LNMY88J.webp"]',
                'nama_barang' => 'Gimbal Stabilizer DJI Ronin-SC',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Aksesoris Kamera',
                'deskripsi_barang' => 'Penyeimbang elektrik agar hasil video dari kamera mirrorless Anda mulus seperti pergerakan kamera di film bioskop.',
                'stok' => rand(1, 20),
                'harga_perhari' => 80000.00,
                'harga_perjam' => 3333.33,
                'catatan_kondisi_barang' => 'Motor gimbal kuat, kalibrasi normal.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 289,
                'gambar_barang' => '["barang/WEZrr2RlHWR9edVxGdzJ5p42LECOpYEhmVhjSsSV.webp","barang/XlFNukcaSpZEetZHv9GXCJUkmE7AnfPKhr4aGXI6.webp","barang/QPkOTla7xxfP902FJOXeBsOokROkKJO5PFQ3bFRh.webp","barang/DzvcEW0DbDORMhhF53UWTpEiuTB5peLULI8oYX2H.webp","barang/GtvTJkyHOcjp7C8NnWinuDpgFesqKt9DqFOW5KSC.webp"]',
                'nama_barang' => 'Tripod Takara ECO-196A',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Aksesoris Kamera',
                'deskripsi_barang' => 'Tripod berbahan aluminium lightweight. Ringan dibawa mendaki tetapi cukup kokoh menopang beban kamera DSLR maupun Mirrorless.',
                'stok' => rand(1, 20),
                'harga_perhari' => 20000.00,
                'harga_perjam' => 833.33,
                'catatan_kondisi_barang' => 'Kunci kaki-kaki seret dan kuat, panhead lancar.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 290,
                'gambar_barang' => '["barang/yoBZzvDoZug1F59do02mDmZFvKjBZWxY2y4zIFgd.jpg","barang/uVLzzDOTBI8qZe38OVHTk3szknUwYK5xVaezmNhR.jpg","barang/sr3j62avKsZHL9B7QIz590YtA6OLhlz2144Gey2J.jpg","barang/wMyYVo3UVP7iEG6mT27eKwDcqnAzUbHWATxVDL9P.jpg","barang/Kzoua4iKpLzZuFbxW08pQGRkF6G7rbunL6bfgjPV.jpg"]',
                'nama_barang' => 'SanDisk Extreme Pro SDXC 128GB',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Aksesoris Kamera',
                'deskripsi_barang' => 'Kartu memori super cepat, wajib digunakan jika penyewa mengambil kamera video bit-rate tinggi.',
                'stok' => rand(1, 20),
                'harga_perhari' => 15000.00,
                'harga_perjam' => 625.00,
                'catatan_kondisi_barang' => 'Pin emas bersih, kecepatan baca/tulis normal.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 291,
                'gambar_barang' => '["barang/2gRUv1zWQjVuihfuGO7Yvc5AbN8iAV2BiR9jRDyO.jpg","barang/wZ3eqEBfaHRjVoS8QoxjbN3ZihoJzMRPRPjh40aa.jpg","barang/DLFaTwsUwQt8FMyawwQ8pgFhAjDMMPn0c480ys91.jpg","barang/OmdxJ85plqRC7VuC6f4MkVVXiydABSfsYP177wbk.jpg","barang/62Dc9X1MhI5TyQE8q6QZnc5Zp1oEi7Te06rTYxtK.jpg"]',
                'nama_barang' => 'Godox LED6BI Litemons Pocket',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lighting',
                'deskripsi_barang' => 'Lampu LED mini saku portable yang suhunya bisa diatur (kuning ke putih). Bisa dipasang di atas bodi kamera.',
                'stok' => rand(1, 20),
                'harga_perhari' => 20000.00,
                'harga_perjam' => 833.33,
                'catatan_kondisi_barang' => 'Semua titik LED menyala, baterai internal normal.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 292,
                'gambar_barang' => '["barang/5xFnd4dZeLloqdZqFzbosyHicrze0WCACfmSUFE8.webp","barang/53U4WupQNVwMtRMUi4Jxg7qPFeSOYYZ7gzYl55xB.webp","barang/Wg3admF4pptZdcqmKWQKgXRtrZxZcQGqyI0ElFxB.webp","barang/vmB18OBtEUCmro0poDeyJ08CfDzihXsV0lDoIk2s.webp","barang/43NhS7R2PSICLE5ozyqYx9rqeCIcJjvOwpkIJqH8.webp"]',
                'nama_barang' => 'Godox SL60W LED Video Light',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lighting',
                'deskripsi_barang' => 'Lampu studio continuous berdaya 60 Watt yang sangat terang. Wajib dipasangkan dengan tripod lampu.',
                'stok' => rand(1, 20),
                'harga_perhari' => 60000.00,
                'harga_perjam' => 2500.00,
                'catatan_kondisi_barang' => 'Kipas pendingin lampu halus, lampu tidak kedip.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 293,
                'gambar_barang' => '',
                'nama_barang' => 'Ring Light Midio 26cm + Stand',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lighting',
                'deskripsi_barang' => 'Lampu melingkar yang memberikan efek cahaya estetik berbentuk bulat di bola mata objek.',
                'stok' => rand(1, 20),
                'harga_perhari' => 25000.00,
                'harga_perjam' => 3750.00,
                'catatan_kondisi_barang' => 'Kabel USB utuh, remote kontrol warna lampu berfungsi.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 294,
                'gambar_barang' => '',
                'nama_barang' => 'Wireless Mic Rode Wireless GO II',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Audio',
                'deskripsi_barang' => 'Mikrofon jepit tanpa kabel isi 2 transmitter. Tinggal pasang di kerah baju untuk mendapatkan suara vlog atau wawancara yang bersih.',
                'stok' => rand(1, 20),
                'harga_perhari' => 90000.00,
                'harga_perjam' => 13500.00,
                'catatan_kondisi_barang' => 'Baterai awet, kedua transmitter tersinkronisasi dengan baik.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 295,
                'gambar_barang' => '',
                'nama_barang' => 'Shotgun Mic Rode VideoMic Pro+',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Audio',
                'deskripsi_barang' => 'Mikrofon yang ditancapkan langsung di atas kamera. Berfungsi menangkap suara fokus dari arah depan.',
                'stok' => rand(1, 20),
                'harga_perhari' => 50000.00,
                'harga_perjam' => 7500.00,
                'catatan_kondisi_barang' => 'Busa peredam angin utuh, kabel audio sensitif normal.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 296,
                'gambar_barang' => '',
                'nama_barang' => 'Saramonic Blink 500 B2 Wireless',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Audio',
                'deskripsi_barang' => 'Alternatif mic wireless dual-channel yang lebih ekonomis namun memiliki karakter suara yang tebal dan jernih.',
                'stok' => rand(1, 20),
                'harga_perhari' => 60000.00,
                'harga_perjam' => 9000.00,
                'catatan_kondisi_barang' => 'Klip jepitan utuh, charging case berfungsi baik.',
                'status_barang' => 'Sedikit',
            ],
            
            // ================== DATA ALAT CAMPING ==================
            [
                'kode_barang' => 297,
                'gambar_barang' => '',
                'nama_barang' => 'Tenda Dome Arpenaz 2 Orang',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Tenda',
                'deskripsi_barang' => 'Tenda camping double layer berkapasitas 2 orang. Sangat kokoh menahan angin kencang dan rembesan air hujan.',
                'stok' => rand(1, 20),
                'harga_perhari' => 40000.00,
                'harga_perjam' => 6000.00,
                'catatan_kondisi_barang' => 'Pasak lengkap, frame utuh tidak ada yang retak, kain bersih.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 298,
                'gambar_barang' => '',
                'nama_barang' => 'Tenda Besar Borneo 4 Orang',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Tenda',
                'deskripsi_barang' => 'Tenda keluarga kapasitas 4 orang dilengkapi dengan teras depan yang luas untuk menaruh barang atau memasak.',
                'stok' => rand(1, 20),
                'harga_perhari' => 60000.00,
                'harga_perjam' => 9000.00,
                'catatan_kondisi_barang' => 'Bebas bocor, resleting lancar, tali pengencang lengkap.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 299,
                'gambar_barang' => '',
                'nama_barang' => 'Tenda Besar Great Outdoor 6 Orang',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Tenda',
                'deskripsi_barang' => 'Tenda dome berukuran jumbo untuk kelompok besar. Atap tinggi membuat ruang gerak di dalam tenda menjadi sangat leluasa.',
                'stok' => rand(1, 20),
                'harga_perhari' => 90000.00,
                'harga_perjam' => 13500.00,
                'catatan_kondisi_barang' => 'Kondisi wangi habis dicuci, jahitan seal aman.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 300,
                'gambar_barang' => '',
                'nama_barang' => 'Sleeping Bag Polar Bulu Eiger',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Tidur',
                'deskripsi_barang' => 'Kantung tidur berbahan polar bulu tebal. Sangat hangat untuk menahan suhu dingin pegunungan di malam hari.',
                'stok' => rand(1, 20),
                'harga_perhari' => 20000.00,
                'harga_perjam' => 3000.00,
                'catatan_kondisi_barang' => 'Resleting normal, bahan bersih and wangi laundry.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 301,
                'gambar_barang' => '',
                'nama_barang' => 'Matras Angin Naturehike',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Tidur',
                'deskripsi_barang' => 'Matras tiup otomatis yang empuk, menghindari badan sakit karena menyentuh permukaan tanah yang bergelombang atau berkerikil.',
                'stok' => rand(1, 20),
                'harga_perhari' => 30000.00,
                'harga_perjam' => 4500.00,
                'catatan_kondisi_barang' => 'Tidak ada kebocoran udara, termasuk pompa portable.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 302,
                'gambar_barang' => '',
                'nama_barang' => 'Kasur Angin Intex King Size',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Tidur',
                'deskripsi_barang' => 'Kasur angin ukuran besar, cocok ditaruh di dalam tenda kapasitas 4-6 orang untuk kenyamanan maksimal.',
                'stok' => rand(1, 20),
                'harga_perhari' => 50000.00,
                'harga_perjam' => 7500.00,
                'catatan_kondisi_barang' => 'Katup udara rapat, beludru atas bersih.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 303,
                'gambar_barang' => '',
                'nama_barang' => 'Kompor Portable Camping Kovar',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Memasak',
                'deskripsi_barang' => 'Kompor lipat mini portable berbahan bakar gas kaleng. Desain anti angin (windproof) dengan pelindung kelopak.',
                'stok' => rand(1, 20),
                'harga_perhari' => 20000.00,
                'harga_perjam' => 3000.00,
                'catatan_kondisi_barang' => 'Pemantik listrik menyala normal, keran gas sensitif baik.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 304,
                'gambar_barang' => '',
                'nama_barang' => 'Nesting Cooking Set DS-308',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Memasak',
                'deskripsi_barang' => 'Satu set panci dan wajan camping berbahan anodized aluminium ringan anti lengket. Lengkap untuk kebutuhan makan berkelompok.',
                'stok' => rand(1, 20),
                'harga_perhari' => 25000.00,
                'harga_perjam' => 3750.00,
                'catatan_kondisi_barang' => 'Gagang panci kokoh, permukaan dalam tidak ada baret parah.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 305,
                'gambar_barang' => '',
                'nama_barang' => 'Nesting DS-200 Cookware Single',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Memasak',
                'deskripsi_barang' => 'Set alat masak mini yang ringkas khusus solo hiker atau mendaki berdua.',
                'stok' => rand(1, 20),
                'harga_perhari' => 15000.00,
                'harga_perjam' => 2250.00,
                'catatan_kondisi_barang' => 'Kondisi lengkap dengan jaring pembungkus.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 306,
                'gambar_barang' => '',
                'nama_barang' => 'Lampa Tenda LED Logu',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Penerangan',
                'deskripsi_barang' => 'Lampu gantung tenda dengan baterai isi ulang. Memiliki kecerahan tinggi dan mode redup untuk tidur.',
                'stok' => rand(1, 20),
                'harga_perhari' => 10000.00,
                'harga_perjam' => 1500.00,
                'catatan_kondisi_barang' => 'Casing mulus, port charger micro USB normal.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 307,
                'gambar_barang' => '',
                'nama_barang' => 'Senter Swat Police Jarak Jauh',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Penerangan',
                'deskripsi_barang' => 'Senter genggam dengan fokus yang bisa diatur (*zoomable*). Sangat terang untuk membelah kabut malam.',
                'stok' => rand(1, 20),
                'harga_perhari' => 15000.00,
                'harga_perjam' => 2250.00,
                'catatan_kondisi_barang' => 'Termasuk charger baterai desktop dan lensa warna konverter.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 308,
                'gambar_barang' => '',
                'nama_barang' => 'Headlamp Petzl Tikkina',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Penerangan',
                'deskripsi_barang' => 'Lampu kepala standar pendakian profesional. Hemat baterai dan posisi sudut sorot bisa ditekuk ke bawah.',
                'stok' => rand(1, 20),
                'harga_perhari' => 30000.00,
                'harga_perjam' => 4500.00,
                'catatan_kondisi_barang' => 'Tali karet kepala masih kencang, kompartemen baterai bersih.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 309,
                'gambar_barang' => '',
                'nama_barang' => 'Powerbank Hippo 20000mAh',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Power',
                'deskripsi_barang' => 'Penyimpan daya kapasitas besar untuk mengisi ulang baterai HP atau lampu tenda selama 2-3 hari di hutan.',
                'stok' => rand(1, 20),
                'harga_perhari' => 20000.00,
                'harga_perjam' => 3000.00,
                'catatan_kondisi_barang' => 'Dual output USB berfungsi, indikator LED menyala presisi.',
                'status_barang' => 'Tersedia',
            ],
            [
                'kode_barang' => 310,
                'gambar_barang' => '',
                'nama_barang' => 'Solar Panel Portable 21W Anker',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Power',
                'deskripsi_barang' => 'Panel surya lipat yang bisa digantung di tas carrier untuk mengisi daya perangkat elektronik langsung dari sinar matahari.',
                'stok' => rand(1, 20),
                'harga_perhari' => 80000.00,
                'harga_perjam' => 12000.00,
                'catatan_kondisi_barang' => 'Kain pembungkus bersih, sirkuit solar cell tidak ada yang retak.',
                'status_barang' => 'Sedikit',
            ],
            [
                'kode_barang' => 311,
                'gambar_barang' => '["barang/CmJ6vVLPY0f2QgerW50hDgb1apzPBNIEKybKalH7.jpg","barang/PVyGShAAU5ogRWUT934o4AkOfCTbiiLUIfdJuUMp.png","barang/BK4ISnneSICdJutcEZKb8zRQoJ13CNBbKbdbDhQM.png","barang/jO6LIjHCRmHTLYDJGyHUw3kdr4kFw93Amc95iLeX.jpg","barang/njIAlInnL41dadF3AEvkyrGtor7YxHEmq4mYYNNW.png"]',
                'nama_barang' => 'Genset Portable Mini Honda 1000W',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Power',
                'deskripsi_barang' => 'Generator listrik mini berbahan bakar bensin untuk kebutuhan event outdoor skala besar di tengah area camping.',
                'stok' => rand(1, 20),
                'harga_perhari' => 250000.00,
                'harga_perjam' => 10416.67,
                'catatan_kondisi_barang' => 'Tarikan starter ringan, output tegangan stabil.',
                'status_barang' => 'Sedikit',
            ]
        ];

        DB::table('barang')->insert($data);
    }
}