<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('barang')->insert([
            ['kode_barang' => 273, 'gambar_barang' => '["barang/0qR31bo3S2eWctZGW8syr8nK8UD75sOJBEyDZKRA.jpg","barang/xtUgfsDQPDQTnq60LeTXw9lZEXR5xct11P8DYoCk.webp","barang/fjzO2hIkIc3LEjKsiB1ff7ZsQvf9Z39mvOnQ7cwP.webp","barang/mQxv2LxTM8HTlp8ccI7elnlhiK8zYJfA9hGLdhF2.webp"]', 'nama_barang' => 'Canon EOS 3000D Kit 18-55mm', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'DSLR Cam', 'deskripsi_barang' => 'Kamera DSLR pemula yang sangat mudah digunakan, ramah baterai, cocok untuk tugas kuliah atau dokumentasi kasual.', 'stok' => 17, 'harga_perhari' => 100000.00, 'harga_perjam' => 4166.67, 'catatan_kondisi_barang' => 'Fisik 90%, fungsi normal, lensa bebas jamur.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 274, 'gambar_barang' => '["barang/ougn1UNB1TVb7Eu0vY8v37BpZFspfdBKDbVx5AV9.png","barang/le4NngNBxVtnIChRNyIplegoSdpwSUQUOviJiu5O.webp","barang/znkYFhSd4lf8x2FpcaYA6ptSdk9VeDOoxZpoOnMZ.webp","barang/TUZLBEyBcqGUkvgB3fzzelv1GP4LnKz0yHBlXxl8.webp"]', 'nama_barang' => 'Canon EOS 850D (Body Only)', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'DSLR Cam', 'deskripsi_barang' => 'DSLR kelas menengah dengan sistem autofokus cepat (45 titik silang), bagus untuk foto aksi atau olahraga.', 'stok' => 15, 'harga_perhari' => 150000.00, 'harga_perjam' => 6250.00, 'catatan_kondisi_barang' => 'Karet grip rapat, sensor bersih, tombol responsif.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 275, 'gambar_barang' => '["barang\/cediabruOHWEPDUPfvdSweQdCNMNMFTEtIyC8Cwz.jpg","barang\/zYWKqCRU0YX2pJfuIM2vZ5fSNAQfoXraSjFA7abm.webp","barang\/a7Eiw7ZnrTAuDKoIzXwtC1evYPjiIQWZ0YJMxBFh.webp","barang\/IlQO8Ia8rparl4v10r9X3zBCcpH5CCLjkKOYXyJ0.webp","barang\/XfyNNLCpC2LcrQA7jo6x3aLlqb2U3z2XXuqx7ZQs.webp"]', 'nama_barang' => 'Nikon D7500 (Body Only)', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'DSLR Cam', 'deskripsi_barang' => 'DSLR semi-profesional yang tangguh di segala cuaca (weather-sealed), sangat handal untuk dibawa hunting foto ke alam liar.', 'stok' => 18, 'harga_perhari' => 180000.00, 'harga_perjam' => 7500.00, 'catatan_kondisi_barang' => 'Shutter count rendah, bodi kokoh, ada sedikit lecet pemakaian wajar.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 276, 'gambar_barang' => '["barang/pDWrbgMpiKRwDfHGNxBIRGsNaJxW3LRdfNYQ0WHG.webp","barang/DEgJewMFuGdhEHS2wMl4txQnqDX6hH3fawYlbMtm.webp","barang/RcHmWwU1hONQuCOC0HmW23EnkyXAvZLmp1i6Ljpb.webp","barang/qDwpZpQLfA2gzUCUTG5IdZflQVkmVEMAkVOWIvlC.webp","barang/LVMDCsQQ8rDaXmi4wx9IWr6NKuV50ZjCsLBXMOAW.webp"]', 'nama_barang' => 'Sony Alpha a6400 (Body Only)', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Mirrorless Cam', 'deskripsi_barang' => 'Mirrorless APS-C paling populer untuk vlogger. Layar bisa ditekuk 180 derajat ke depan dan autofokusnya mengunci mata secara real-time.', 'stok' => 10, 'harga_perhari' => 150000.00, 'harga_perjam' => 6250.00, 'catatan_kondisi_barang' => 'Sensor bersih, layar no-vignette, siap pakai.', 'status_barang' => 'Sedikit'],
            ['kode_barang' => 277, 'gambar_barang' => '["barang\/Fhh2keyCvRdB5WtTNwgUuX3eXcm4lzARZ80cETbO.webp","barang\/FHbNBlOthhIF9jHURmu7fjcFpCDAmnlQRIUTm2JO.webp","barang\/5uSSVTEOxPh1HqYaNZGKsfom7TPToMpAOtYvMi7f.webp","barang\/ZzIoyLcrRMWJXikt7jVJYana7sjDYUCbyBK4vlE5.webp"]', 'nama_barang' => 'Sony Alpha A7 III (Body Only)', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Mirrorless Cam', 'deskripsi_barang' => 'Kamera Full-Frame standar industri rental. Sangat kuat untuk foto komersial, wedding, maupun video cinematic di kondisi minim cahaya.', 'stok' => 11, 'harga_perhari' => 300000.00, 'harga_perjam' => 12500.00, 'catatan_kondisi_barang' => 'Karet jempol agak melar dikit, fungsi 100% normal, sensor bersih.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 278, 'gambar_barang' => '["barang\/RdU4VaCJaCa7U4wgg6AHoRYMKwkzoBlRMd8qI9OX.webp","barang\/vtZ6HdsvaX2bO1Fwe3ds3vJiEHV77QWPROzl8ohk.webp","barang\/6oyiDU179Co1M12bpHrAFDLYMp2wK1IkgSgf5u8z.webp","barang\/SbrGqLlv1OL2BgosEe12kdj2gQh3vP5cyRp0s0VY.webp","barang\/e1q2MMjS89uTbb6zuh6Sa97kYfPXOCDwGTm84QKb.webp"]', 'nama_barang' => 'Fujifilm X-T30 II (Body Only)', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Mirrorless Cam', 'deskripsi_barang' => 'Kamera mirrorless dengan desain retro yang estetik. Keunggulannya punya Film Simulation bawaan, jadi hasil foto tidak perlu diedit lagi.', 'stok' => 18, 'harga_perhari' => 140000.00, 'harga_perjam' => 5833.33, 'catatan_kondisi_barang' => 'Mulus total, semua dial berfungsi dengan presisi.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 279, 'gambar_barang' => '["barang\/NGmyMRd9F3mcbccoTBbcchYvpnhZIxekUgJTe88m.webp","barang\/HBuKmkhJwCW2TlsXzXumSviIZ54rJ70NHmeUxfem.webp","barang\/aoVFf972yDukZp5KG16K2YpYGsqH54cFQg8r20PR.webp","barang\/KpalZ7VAbLU8anl6v5UCQ6RlE2WOvgYiYQ8sIuTn.webp","barang\/LWM3q63GcrKGsoUJftSlrqhoAv6myaIzr3kXOkex.webp"]', 'nama_barang' => 'Sony FX30 Cinema Line', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Video Cam', 'deskripsi_barang' => 'Kamera berspesifikasi bioskop mini. Memiliki kipas internal jadi anti-overheat saat dipakai syuting seharian penuh.', 'stok' => 3, 'harga_perhari' => 250000.00, 'harga_perjam' => 10416.67, 'catatan_kondisi_barang' => 'Lengkap dengan top handle, lubang ulir baut cage aman.', 'status_barang' => 'Sedikit'],
            ['kode_barang' => 281, 'gambar_barang' => '["barang\/ZSydCk48wmkMWMJ4bEC81iws78hBHv0VBliUb12l.jpg","barang\/QYzpqCnp5QchdbAWULDdvkwSmvHDFdnOTjDp4cxt.jpg","barang\/vG0UnnAO8nksSbGdmDuf4DU7N1zhRirEaOkSgupT.jpg","barang\/K5aDyg7XpwBWTXFVUDctFkKjFN6GM1kheHVQnSLy.jpg","barang\/pfOVg1UXcepLIkWDhW63grlRRLul4mDMNMvPk1vC.jpg"]', 'nama_barang' => 'BMPCC 4K (Pocket Cinema)', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Video Cam', 'deskripsi_barang' => 'Khusus untuk videografer profesional yang ingin hasil video mentah (RAW) dengan warna sinematik tingkat tinggi.', 'stok' => 3, 'harga_perhari' => 280000.00, 'harga_perjam' => 11666.67, 'catatan_kondisi_barang' => 'Layar sentuh normal, baterai bawaan agak boros.', 'status_barang' => 'Sedikit'],
            ['kode_barang' => 282, 'gambar_barang' => '["barang\/yHqmMP7UxrKlNdkVH63Qp1iuOQFmTxNNmr3m7RWN.jpg","barang\/ymWvJmyLpn02mMfLkhv9VYqo0Wdz9KjugfPndi37.png","barang\/Z6rTUoZIxhtb9yo7PH3DlV0rVbrXYKcTZ6ywa4Bj.png","barang\/FC3Oe6yA8CEb9XVprdpFVcFPrMw3PxCrY4VumUwJ.png","barang\/pj7H3vhHU0F7gZuZ4g00y8NI91LNMAieXgRsCMqh.png"]', 'nama_barang' => 'GoPro Hero 12 Black', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Action Cam', 'deskripsi_barang' => 'Kamera aksi kasta tertinggi. Sangat cocok dipasangkan ke helm motovlog atau dibawa basah-basahan saat camping di air terjun.', 'stok' => 6, 'harga_perhari' => 120000.00, 'harga_perjam' => 5000.00, 'catatan_kondisi_barang' => 'Lencana depan dipasang tempered glass, backdoor rapat anti air.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 283, 'gambar_barang' => '["barang\/EsEBIFSlrxdRnkffvFkz488wXxsy3cvtbpHIALk4.webp","barang\/nZb3tbJfcIThSvCSwR7g1Lcz7zGu9IcmfSfh5gyf.jpg","barang\/JljdGa2Pqaz105WaH01rEElJm13ivYtvFU6WyE1r.jpg","barang\/uxnVxyVuatPhJeNo4qO1PnFYZ92C9cYkXoXchAlG.jpg","barang\/VDMU218hmvIQJClM2zhjlWPzZySwh9BtMwrLL5Fn.jpg"]', 'nama_barang' => 'DJI Osmo Action 4', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Action Cam', 'deskripsi_barang' => 'Saingan berat GoPro dengan sensor lebih besar, sangat unggul untuk merekam aksi outdoor di sore atau malam hari.', 'stok' => 7, 'harga_perhari' => 100000.00, 'harga_perjam' => 4166.67, 'catatan_kondisi_barang' => 'Mount magnetik kuat, bodi mulus.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 284, 'gambar_barang' => '["barang\/zDgt7yqD84GUxHZ41zideWGibvP8lzHcTTVhCHJt.webp","barang\/XXhIYg2zCz82nR663IdQ1InZMW19Kp7sHJiKh5XA.jpg","barang\/5fTUyX2U4ureB4Iomjj5xn82EcQU8UaD6x04xL6m.jpg","barang\/6oVPlMgvd4ZMkmDWvzYlRkdoshMOAeX8UzbYoK5U.jpg","barang\/bsKV8zwYqH7CGyHAmdEEb24QC6rY9IYAY28IxYMG.jpg"]', 'nama_barang' => 'Insta360 X3', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Action Cam', 'deskripsi_barang' => 'Kamera aksi 360 derajat. Bisa merekam segala arah sekaligus, cocok untuk membuat konten kreatif tanpa pusing memikirkan arah kamera.', 'stok' => 15, 'harga_perhari' => 130000.00, 'harga_perjam' => 5416.67, 'catatan_kondisi_barang' => 'Lensa cembung mulus tanpa baret (wajib pakai lens guard).', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 285, 'gambar_barang' => '["barang\/pYv8baqEDGNyuxmFPm0xqig4pornaT4OQ9RfZ8y2.webp","barang\/JjTzB1ZUiiN4VR7gzQEz7hEIFKYmH9UWz2OnsI6o.webp","barang\/I7VkpZkSjEwipoUHZpbxADVFVTYlggXzaFNXDHFW.webp","barang\/Z7HuMKh9x8q0Y2EbO1XgPZTS5N1xnx46W1bAvyXL.webp"]', 'nama_barang' => 'Sigma 16mm f/1.4 DC DN (Sony E)', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Lensa', 'deskripsi_barang' => 'Lensa lebar premium. Sangat tajam, pas sekali dipasang ke Sony a6400 atau FX30 untuk vlogging jarak dekat atau foto pemandangan malam bintang.', 'stok' => 7, 'harga_perhari' => 60000.00, 'harga_perjam' => 2500.00, 'catatan_kondisi_barang' => 'Optik bersih, no fog, no jamur.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 286, 'gambar_barang' => '["barang\/WdBTDym8fpZnMwg3uGhAbE1ykup1ZvAC9rKqjJS4.webp","barang\/QQNrifEPnbMbtMEFF6iUVneoHd7CjPdjGGnMvBoE.jpg","barang\/zDQUHrjAdsPT7FoJPI3x5DYaTTMXAA8XgXQH5wyx.jpg","barang\/fhhl8zmjcG3Rj3sGBP17KPM1wR36Tcz4nct2Ff1o.jpg","barang\/jbhbpdWYULomAig3wflr2exXsOPSFu5eokO8FX8q.jpg"]', 'nama_barang' => 'Sony FE 50mm f/1.8', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Lensa', 'deskripsi_barang' => 'Lensa potret esensial. Memberikan efek latar belakang blur (bokeh) yang sangat halus untuk memisahkan objek dengan objek di belakangnya.', 'stok' => 12, 'harga_perhari' => 40000.00, 'harga_perjam' => 1666.67, 'catatan_kondisi_barang' => 'Fokus cepat, kelengkapan lensa + hood.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 287, 'gambar_barang' => '["barang\/491oiPVSc5ebn1oejYhAI0fakJv7snQyhczJkk33.webp","barang\/daZBKCxxL74Lb4g2HP1bivkn8oYQl0jH3IQZ4mxm.jpg","barang\/P9hoDaIoyLmVZJ3OiBIH0QliCMTl2nyvkJu9dW14.jpg","barang\/vaDk8M2p3kcQ1lnKbCtelkl4lipZfQeNyNxi203L.jpg","barang\/NqsS6BNeqdKDi1bbeWHj62IskcRiEqa2hFxMMam8.jpg"]', 'nama_barang' => 'Tamron 28-75mm f/2.8 G2 (Sony E)', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Lensa', 'deskripsi_barang' => 'Lensa zoom serbaguna bukaan konstan f/2.8. Ini adalah upgrade terbaik untuk menggantikan lensa bawaan (kit) bagi pengguna Sony A7 III.', 'stok' => 10, 'harga_perhari' => 100000.00, 'harga_perjam' => 4166.67, 'catatan_kondisi_barang' => 'Karet kencang, fungsi zoom smooth.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 288, 'gambar_barang' => '["barang\/T3yVpNbDODy6BiJA40DUjUntuzcPp2X7eTwslpcq.webp","barang\/e84vdORBhndi3ToqeC8u1VRYg6yYtAccp7j8ipyZ.webp","barang\/dETvgyzdnYXYuT0oLm4C6Y7G9D6weoh888FkErbL.webp"]', 'nama_barang' => 'Gimbal Stabilizer DJI Ronin-SC', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Aksesoris Kamera', 'deskripsi_barang' => 'Penyeimbang elektrik agar hasil video dari kamera mirrorless Anda mulus seperti pergerakan kamera di film bioskop.', 'stok' => 6, 'harga_perhari' => 80000.00, 'harga_perjam' => 3333.33, 'catatan_kondisi_barang' => 'Motor gimbal kuat, kalibrasi normal.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 289, 'gambar_barang' => '["barang\/WEZrr2RlHWR9edVxGdzJ5p42LECOpYEhmVhjSsSV.webp","barang\/nEq1uS5Wpyw8ucWwSvGBw6Wu5jgcea0IGNAwIkIK.webp","barang\/Vqv0isJGnIPlLlwp9d5NWS9T7X3YDOdSTzt6cQ2F.webp","barang\/RVlqZPALqgFt8Rn2muw1N5uBJ3kWRfILT1wP29E8.webp","barang\/JUKPEBsiif50cBk0eTrSw2nxiaonDko9WDl0ZXWW.webp"]', 'nama_barang' => 'Tripod Takara ECO-196A', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Aksesoris Kamera', 'deskripsi_barang' => 'Tripod berbahan aluminium lightweight. Ringan dibawa mendaki tetapi cukup kokoh menopang beban kamera DSLR maupun Mirrorless.', 'stok' => 2, 'harga_perhari' => 20000.00, 'harga_perjam' => 833.33, 'catatan_kondisi_barang' => 'Kunci kaki-kaki seret dan kuat, panhead lancar.', 'status_barang' => 'Sedikit'],
            ['kode_barang' => 290, 'gambar_barang' => '["barang\/bB5erZurHnsigPum7z8osjWTotJCovFUpLriBiMv.png","barang\/UeaHzK4RTtEdTp5hhfQfVprjrAqGnwwVOBkk7eQF.png","barang\/B1hUaDQBWwVPE7HtRnFlN3MIsFxBMSDpXUrVbzdH.png","barang\/wMyYVo3UVP7iEG6mT27eKwDcqnAzUbHWATxVDL9P.jpg"]', 'nama_barang' => 'SanDisk Extreme Pro SDXC 128GB', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Aksesoris Kamera', 'deskripsi_barang' => 'Kartu memori super cepat, wajib digunakan jika penyewa mengambil kamera video bit-rate tinggi.', 'stok' => 15, 'harga_perhari' => 15000.00, 'harga_perjam' => 625.00, 'catatan_kondisi_barang' => 'Pin emas bersih, kecepatan baca/tulis normal.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 291, 'gambar_barang' => '["barang\/2gRUv1zWQjVuihfuGO7Yvc5AbN8iAV2BiR9jRDyO.jpg","barang\/lqTVbo1ejLlbCl5jagZnGKqB1d3Qof9xcQ3FK6LA.jpg","barang\/AFPU4uAGjXPbAQWTB1iMPVJNbu37Q1HqKkTbU5y4.jpg","barang\/4Qm1SRhYHh3Vs2uKinovSnZtiRLvxTbzpv0seAhb.jpg"]', 'nama_barang' => 'Godox LED6BI Litemons Pocket', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Lighting', 'deskripsi_barang' => 'Lampu LED mini saku portable yang suhunya bisa diatur (kuning ke putih). Bisa dipasang di atas bodi kamera.', 'stok' => 9, 'harga_perhari' => 20000.00, 'harga_perjam' => 833.33, 'catatan_kondisi_barang' => 'Semua titik LED menyala, baterai internal normal.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 292, 'gambar_barang' => '["barang\/5xFnd4dZeLloqdZqFzbosyHicrze0WCACfmSUFE8.webp","barang\/C7OyVJ36wd4y1gvEyK3ucaYcdjAVNpkj5l86VlUF.jpg","barang\/CoWTYfCzAESBL5Vwb4GmjylyQsLJuUY6tIbvTZgl.webp","barang\/F5XaLah42TcFUCRE9tWpGWtM7CIWqEYQ8vFElvlA.webp"]', 'nama_barang' => 'Godox SL60W LED Video Light', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Lighting', 'deskripsi_barang' => 'Lampu studio continuous berdaya 60 Watt yang sangat terang. Wajib dipasangkan dengan tripod lampu.', 'stok' => 20, 'harga_perhari' => 60000.00, 'harga_perjam' => 2500.00, 'catatan_kondisi_barang' => 'Kipas pendingin lampu halus, lampu tidak kedip.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 293, 'gambar_barang' => '["barang\/AXVVrK3IZpkrY8FCW1UVZIX8js2NT8aIGnJPA9GS.webp","barang\/Id1WZuM9uKWfTdnOWsjgrJljo100lsq9UY9mloeG.jpg","barang\/zb1BK74nKRGNxbvyPPr3J5rjiTPRfPhsuP2HJfFQ.jpg","barang\/xmO0v1rpieIWvKtgWtSJSULkI2YWfn3DyMbTw2mw.jpg","barang\/WNslTH4YoxMRZBBLE4gpgSW786zpGhsqR4TigAPS.jpg"]', 'nama_barang' => 'Ring Light Midio 26cm + Stand', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Lighting', 'deskripsi_barang' => 'Lampu melingkar yang memberikan efek cahaya estetik berbentuk bulat di bola mata objek.', 'stok' => 6, 'harga_perhari' => 25000.00, 'harga_perjam' => 1041.67, 'catatan_kondisi_barang' => 'Kabel USB utuh, remote kontrol warna lampu berfungsi.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 294, 'gambar_barang' => '["barang\/UeFCjyZgsZlzTDguiaWdMmfDk88q3sgyF8QBXFeJ.jpg","barang\/67HfJcuXhEhelMjwUwEoxD24WYCyVYoF61VdHYgY.jpg","barang\/3E8y7lG6iFIA9VV9EkYERGV0YMwZo3LXLSjfE9C3.jpg","barang\/PERGsZr2KAiZMyYm7rURFM74aLcddp9mXEv5L9k3.jpg","barang\/psI7iAWU39MRRu5bZmwFES3HmUJmK7K6pz3qNRdL.jpg"]', 'nama_barang' => 'Wireless Mic Rode Wireless GO II', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Audio', 'deskripsi_barang' => 'Mikrofon jepit tanpa kabel isi 2 transmitter. Tinggal pasang di kerah baju untuk mendapatkan suara vlog atau wawancara yang bersih.', 'stok' => 17, 'harga_perhari' => 90000.00, 'harga_perjam' => 3750.00, 'catatan_kondisi_barang' => 'Baterai awet, kedua transmitter tersinkronisasi dengan baik.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 295, 'gambar_barang' => '["barang\/rOVdNfUNPg4P9JFJIqqa8NO4HF1iohvNxJpXXLVE.jpg","barang\/8iSOTDu9Zbfo9ueFmHX5Mi73bxfYnDkJSeFmHpAo.jpg","barang\/kvZmFCY2MznSvKDgX0oO558rwH8vxOcI8soIY3q4.jpg","barang\/YRcfzpkMWRCO0N53J5K9ITpYMUcn4XZ6T6FQuGX3.jpg","barang\/TtaxFf3scAeD7alc4exQqkUEYjjGB05VWz007YeS.jpg"]', 'nama_barang' => 'Shotgun Mic Rode VideoMic Pro+', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Audio', 'deskripsi_barang' => 'Mikrofon yang ditancapkan langsung di atas kamera. Berfungsi menangkap suara fokus dari arah depan.', 'stok' => 5, 'harga_perhari' => 50000.00, 'harga_perjam' => 2083.33, 'catatan_kondisi_barang' => 'Busa peredam angin utuh, kabel audio sensitif normal.', 'status_barang' => 'Sedikit'],
            ['kode_barang' => 296, 'gambar_barang' => '["barang\/37ySu42XDfDrRgw3chtXuc0iPjQykBm8wwDZvlRd.webp","barang\/Lq5nqfQAArALBDqzb306U3KWMiyRC66AQhtrMOt4.webp","barang\/oCmkPHU6uPu7Bz8IJQdtPjjVEKuafVQfI3SAd1sg.webp","barang\/9XlnsfNRhN9h415ELukzgSX4A2CurCw56K7dkVtx.webp"]', 'nama_barang' => 'Saramonic Blink 500 B2 Wireless', 'kategori_barang' => 'Kamera', 'subkategori_barang' => 'Audio', 'deskripsi_barang' => 'Alternatif mic wireless dual-channel yang lebih ekonomis namun memiliki karakter suara yang tebal dan jernih.', 'stok' => 13, 'harga_perhari' => 60000.00, 'harga_perjam' => 2500.00, 'catatan_kondisi_barang' => 'Klip jepitan utuh, charging case berfungsi baik.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 297, 'gambar_barang' => '["barang\/OnymcAPYdQbHeVg4C6rTP67I79Hsvyv4LPRCRcx9.webp","barang\/fC5VcIEX7UGCWHJWf5Qg0aYap3oJCJJYccDgfoIH.jpg","barang\/wSciCdWn5glGHZZMwFYrCSeecRBQYWaV7bxoHVBG.webp","barang\/658T7wzE5qWlmbE0qGZmrTrIacsTsxA3u7P5v4j2.jpg"]', 'nama_barang' => 'Tenda Dome Arpenaz 2 Orang', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Tenda', 'deskripsi_barang' => 'Tenda camping double layer berkapasitas 2 orang. Sangat kokoh menahan angin kencang dan rembesan air hujan.', 'stok' => 10, 'harga_perhari' => 40000.00, 'harga_perjam' => 1666.67, 'catatan_kondisi_barang' => 'Pasak lengkap, frame utuh tidak ada yang retak, kain bersih.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 298, 'gambar_barang' => '["barang\/f4raioKZU5UNkCVBkJtoFMKGTB7GfNpIhbi4MWd7.jpg","barang\/4wsTjg14VJj0DgkiZS7gQN87ceEI6qc8at8cN3My.jpg","barang\/s3x6eKvzKPbnc38vEbPoxThCZPYy5EqCZbyIZ7JF.jpg"]', 'nama_barang' => 'Tenda Besar Borneo 4 Orang', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Tenda', 'deskripsi_barang' => 'Tenda keluarga kapasitas 4 orang dilengkapi dengan teras depan yang luas untuk menaruh barang atau memasak.', 'stok' => 8, 'harga_perhari' => 60000.00, 'harga_perjam' => 2500.00, 'catatan_kondisi_barang' => 'Bebas bocor, resleting lancar, tali pengencang lengkap.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 299, 'gambar_barang' => '["barang\/ukXbZyVMVnosI3DazyovWxE1YqXWZqO5YmLTNStl.jpg","barang\/5T8EWQkj1ceT9hfrKG3GqoPaRwrED97oOgqQ55cP.jpg","barang\/ftGC6JOaUcOwgRV7CmSRqu62z9J3VyK7G5dXq2aD.jpg","barang\/pIdzk8fsS2NGHnLRepBpSHtNuOLavNJ8jBWyYnvs.jpg"]', 'nama_barang' => 'Tenda Besar Great Outdoor 6 Orang', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Tenda', 'deskripsi_barang' => 'Tenda dome berukuran jumbo untuk kelompok besar. Atap tinggi membuat ruang gerak di dalam tenda menjadi sangat leluasa.', 'stok' => 19, 'harga_perhari' => 90000.00, 'harga_perjam' => 3750.00, 'catatan_kondisi_barang' => 'Kondisi wangi habis dicuci, jahitan seal aman.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 300, 'gambar_barang' => '["barang\/XhA8tbXnX71ROULbEATavFdhkliksirlKwKziLm1.jpg","barang\/TpuCGxw4c0ITM7JZdvl9qB5JOWDrSicLxR3DJXVh.jpg","barang\/wH3T7Wan9aey9gFl8HwWFXRfvpGDUpdF7acVDhPl.jpg"]', 'nama_barang' => 'Sleeping Bag Polar Bulu Eiger', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Peralatan Tidur', 'deskripsi_barang' => 'Kantung tidur berbahan polar bulu tebal. Sangat hangat untuk menahan suhu dingin pegunungan di malam hari.', 'stok' => 11, 'harga_perhari' => 20000.00, 'harga_perjam' => 833.33, 'catatan_kondisi_barang' => 'Resleting normal, bahan bersih and wangi laundry.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 301, 'gambar_barang' => '["barang\/LxpDhgTFXlxnnAptndH3s4UJET2aVUmJI2CWBfmS.jpg","barang\/NGcuEyToTAynpWlIyY2Li7ar19iIkGlXiL8nNOMB.webp","barang\/VyZOcoMPGshmP2ZmAkLezUlYYQ4ibMX4MryoOM76.webp"]', 'nama_barang' => 'Matras Angin Naturehike', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Peralatan Tidur', 'deskripsi_barang' => 'Matras tiup otomatis yang empuk, menghindari badan sakit karena menyentuh permukaan tanah yang bergelombang atau berkerikil.', 'stok' => 18, 'harga_perhari' => 30000.00, 'harga_perjam' => 1250.00, 'catatan_kondisi_barang' => 'Tidak ada kebocoran udara, termasuk pompa portable.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 302, 'gambar_barang' => '["barang\/2eKUlLmaKyXm75d0ymUaEu9aOOsRACrnL3dZOGWJ.jpg","barang\/yN08JIg9zMWeMYiYl0FYdyt5eHUEs5iV0OqAwrEU.jpg"]', 'nama_barang' => 'Kasur Angin Intex King Size', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Peralatan Tidur', 'deskripsi_barang' => 'Kasur angin ukuran besar, cocok ditaruh di dalam tenda kapasitas 4-6 orang untuk kenyamanan maksimal.', 'stok' => 10, 'harga_perhari' => 50000.00, 'harga_perjam' => 2083.33, 'catatan_kondisi_barang' => 'Katup udara rapat, beludru atas bersih.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 303, 'gambar_barang' => '["barang\/cR10569b7B9sBOJhoNgZkvC7zPPmCHabJCXxytOo.jpg","barang\/fztUc8AiseIBQocUyh5JfgnoIcOwqA45Nii6zaSf.webp","barang\/Wz4GHbB9hUaXecvLpb2WignBO94WrisXvaTO9zgo.webp"]', 'nama_barang' => 'Kompor Portable Camping Kovar', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Peralatan Memasak', 'deskripsi_barang' => 'Kompor lipat mini portable berbahan bakar gas kaleng. Desain anti angin (windproof) dengan pelindung kelopak.', 'stok' => 8, 'harga_perhari' => 20000.00, 'harga_perjam' => 833.33, 'catatan_kondisi_barang' => 'Pemantik listrik menyala normal, keran gas sensitif baik.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 304, 'gambar_barang' => '["barang\/Y5BzCU3mNyVMLWpMa0cweLQHIQMGi4E4L6Qb7kdV.jpg","barang\/Q1LoKwA81adjGR4IVpBbdWOYxtWxbqWYW5EKz0OK.jpg","barang\/VHMs4js9QXX6DGnmWH0ZdVpjCQbYlnhaUUuRDER7.jpg","barang\/eMVCWLURiCoID16TkncM1NofbQhXgFodcw1T9l81.jpg"]', 'nama_barang' => 'Nesting Cooking Set DS-308', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Peralatan Memasak', 'deskripsi_barang' => 'Satu set panci dan wajan camping berbahan anodized aluminium ringan anti lengket. Lengkap untuk kebutuhan makan berkelompok.', 'stok' => 18, 'harga_perhari' => 25000.00, 'harga_perjam' => 1041.67, 'catatan_kondisi_barang' => 'Gagang panci kokoh, permukaan dalam tidak ada baret parah.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 305, 'gambar_barang' => '["barang\/e855cdBLuTEEjUayeYRFBwI1A80V9tdmxj23Tuxa.jpg","barang\/UAf4cybxg4GvAgOPYh7GSV98iGG6AOprQiE3KujF.webp"]', 'nama_barang' => 'Nesting DS-200 Cookware Single', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Peralatan Memasak', 'deskripsi_barang' => 'Set alat masak mini yang ringkas khusus solo hiker atau mendaki berdua.', 'stok' => 4, 'harga_perhari' => 15000.00, 'harga_perjam' => 625.00, 'catatan_kondisi_barang' => 'Kondisi lengkap dengan jaring pembungkus.', 'status_barang' => 'Sedikit'],
            ['kode_barang' => 306, 'gambar_barang' => '["barang\/YPEgifItt6cL2Zj3UyNbagTRWtQkBRpll3W0o5SN.jpg","barang\/X8oiogByhXckicSpXHIZH8WEyqEMMCFqz6vPcrPd.webp","barang\/q0Bg8wMg0I9KIiXbSZxofRelhjiezSngvCA9rZej.webp"]', 'nama_barang' => 'Lampa Tenda LED Logu', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Penerangan', 'deskripsi_barang' => 'Lampu gantung tenda dengan baterai isi ulang. Memiliki kecerahan tinggi dan mode redup untuk tidur.', 'stok' => 19, 'harga_perhari' => 10000.00, 'harga_perjam' => 416.67, 'catatan_kondisi_barang' => 'Casing mulus, port charger micro USB normal.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 307, 'gambar_barang' => '["barang\/YIyGnKPOZkQLd7Zd2Mzzb1IaHjtheQk9IUhcgbce.webp","barang\/2ID4fvYsnmtIkSyigWs0YtmNhSOzOZoG3MBFQKY1.webp","barang\/8v2i9MQ8q63bYP5GOkvB1WMR2KyAUnadtn5wIqYr.webp"]', 'nama_barang' => 'Senter Swat Police Jarak Jauh', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Penerangan', 'deskripsi_barang' => 'Senter genggam dengan fokus yang bisa diatur (*zoomable*). Sangat terang untuk membelah kabut malam.', 'stok' => 15, 'harga_perhari' => 15000.00, 'harga_perjam' => 625.00, 'catatan_kondisi_barang' => 'Termasuk charger baterai desktop dan lensa warna konverter.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 308, 'gambar_barang' => '["barang\/zGsrihEEizluF09wSRxqmGBXP8bG6VegigYaaoJN.jpg","barang\/INsIJCSbTj5aVeKdbzTN4CPhWUcomGaz6Ru6k8A2.webp","barang\/SMjvjuylwmVqHZhdCmqKQzUi9V6S4Lwx8IKAMfdh.webp"]', 'nama_barang' => 'Headlamp Petzl Tikkina', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Penerangan', 'deskripsi_barang' => 'Lampu kepala standar pendakian profesional. Hemat baterai dan posisi sudut sorot bisa ditekuk ke bawah.', 'stok' => 6, 'harga_perhari' => 30000.00, 'harga_perjam' => 1250.00, 'catatan_kondisi_barang' => 'Tali karet kepala masih kencang, kompartemen baterai bersih.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 309, 'gambar_barang' => '["barang\/wpMn4He8hJ3P8UReH8MLh5W5wS0FtnNRdHW1WT0E.webp","barang\/PDAW773tCMHWpqVGklyDr5n5RTd77jxgB9GVmpD8.webp","barang\/fhV0wSDaIO96u7BtqH8Aq9nI1dQwtdLtV5oCYCGV.webp","barang\/4UuFAtgKORIvAGpQr2GqMpzUJa8BxaSKVKMGAZYD.webp"]', 'nama_barang' => 'Powerbank Hippo 20000mAh', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Power', 'deskripsi_barang' => 'Penyimpan daya kapasitas besar untuk mengisi ulang baterai HP atau lampu tenda selama 2-3 hari di hutan.', 'stok' => 19, 'harga_perhari' => 20000.00, 'harga_perjam' => 833.33, 'catatan_kondisi_barang' => 'Dual output USB berfungsi, indikator LED menyala presisi.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 310, 'gambar_barang' => '["barang\/OL730LspWCrDTQs2VIkJg4mgQ9vGZq6T49rpkDiE.webp","barang\/Vyn3e04aVEA7M3wbusxfG1jYyAiZHo2K0DVmZOzJ.jpg","barang\/k89bfqawB9cqSogdA1xzNcqgihHEZuqaDUW3WjFR.jpg"]', 'nama_barang' => 'Solar Panel Portable 21W Anker', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Power', 'deskripsi_barang' => 'Panel surya lipat yang bisa digantung di tas carrier untuk mengisi daya perangkat elektronik langsung dari sinar matahari.', 'stok' => 6, 'harga_perhari' => 80000.00, 'harga_perjam' => 3333.33, 'catatan_kondisi_barang' => 'Kain pembungkus bersih, sirkuit solar cell tidak ada yang retak.', 'status_barang' => 'Tersedia'],
            ['kode_barang' => 311, 'gambar_barang' => '["barang\/clhHOvjNCOHRxDZT0bgmGFMESnfNT8XapD6FN18u.webp","barang\/MiYbCkl5Fx19SjSF4hUTGip9Ws3zB64rp25sqDKc.webp","barang\/3Yl4QvpwQ2JWpRLpm5ez9paygrEoukGiq07020h9.jpg"]', 'nama_barang' => 'Genset Portable Mini Honda 1000W', 'kategori_barang' => 'Alat Camping', 'subkategori_barang' => 'Power', 'deskripsi_barang' => 'Generator listrik mini berbahan bakar bensin untuk kebutuhan event outdoor skala besar di tengah area camping.', 'stok' => 7, 'harga_perhari' => 250000.00, 'harga_perjam' => 10416.67, 'catatan_kondisi_barang' => 'Tarikan starter ringan, output tegangan stabil.', 'status_barang' => 'Tersedia'],
        ]);
    }
}