<?php

namespace Database\Seeders;

use App\Models\Barang;
use Illuminate\Database\Seeder;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        $barangs = [
            // KATEGORI: KAMERA (15 Barang)
            [
                'gambar_barang' => ['images/camera.jpg'],
                'nama_barang' => 'Canon EOS 90D Kit 18-135mm',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'DSLR Cam',
                'deskripsi_barang' => 'Kamera DSLR resolusi tinggi 32.5 MP dengan perekaman video 4K, sangat cocok untuk dokumentasi event profesional.',
                'stok' => 4,
                'harga_perhari' => 150000.00,
                'harga_perjam' => 20000.00,
                'catatan_kondisi_barang' => 'Fungsi normal, sensor bersih, lensa bebas jamur.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camera.jpg'],
                'nama_barang' => 'Sony Alpha 7 IV (Body Only)',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Mirrorless Cam',
                'deskripsi_barang' => 'Kamera mirrorless full-frame berspesifikasi tinggi, andalan para videografer profesional.',
                'stok' => 2,
                'harga_perhari' => 300000.00,
                'harga_perjam' => 40000.00,
                'catatan_kondisi_barang' => 'Kondisi mulus, kelengkapan baterai original dan strap.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camera.jpg'],
                'nama_barang' => 'Fujifilm X-T4 Kit 18-55mm',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Mirrorless Cam',
                'deskripsi_barang' => 'Kamera mirrorless dengan warna khas Fujifilm yang menawan dan sudah dilengkapi stabilizer internal (IBIS).',
                'stok' => 3,
                'harga_perhari' => 200000.00,
                'harga_perjam' => 25000.00,
                'catatan_kondisi_barang' => 'Layar aman tidak vignet, baterai awet.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camera.jpg'],
                'nama_barang' => 'Panasonic Lumix GH5',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Video Cam',
                'deskripsi_barang' => 'Kamera khusus video profesional dengan dukungan perekaman internal 10-bit tanpa batas waktu.',
                'stok' => 2,
                'harga_perhari' => 180000.00,
                'harga_perjam' => 25000.00,
                'catatan_kondisi_barang' => 'Body ada lecet pemakaian wajar, performa video lancar jaya.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camera.jpg'],
                'nama_barang' => 'GoPro Hero 11 Black',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Action Cam',
                'deskripsi_barang' => 'Action cam tahan air untuk aktivitas outdoor eksterm dengan kestabilan video HyperSmooth 5.0.',
                'stok' => 5,
                'harga_perhari' => 90000.00,
                'harga_perjam' => 15000.00,
                'catatan_kondisi_barang' => 'Sudah termasuk mounting helm/dada dan pelindung anti air.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camera.jpg'],
                'nama_barang' => 'DJI Pocket 2 Creator Combo',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Action Cam',
                'deskripsi_barang' => 'Kamera saku mungil dengan gimbal stabilizer 3-axis terintegrasi untuk vlogging super praktis.',
                'stok' => 3,
                'harga_perhari' => 100000.00,
                'harga_perjam' => 15000.00,
                'catatan_kondisi_barang' => 'Mic wireless bawaan lengkap, lensa jernih.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/lens.jpg'],
                'nama_barang' => 'Lensa Sony FE 24-70mm f/2.8 GM',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lensa',
                'deskripsi_barang' => 'Lensa zoom premium lini G-Master Sony dengan bukaan konstan f/2.8, tajam di setiap fokal.',
                'stok' => 2,
                'harga_perhari' => 250000.00,
                'harga_perjam' => 35000.00,
                'catatan_kondisi_barang' => 'Karet kencang, optik bersih dari jamur dan fog.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/lens.jpg'],
                'nama_barang' => 'Lensa Canon EF 50mm f/1.8 STM',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lensa',
                'deskripsi_barang' => 'Lensa prime legendaris untuk foto portrait dengan efek background blur (bokeh) yang menawan.',
                'stok' => 6,
                'harga_perhari' => 40000.00,
                'harga_perjam' => 5000.00,
                'catatan_kondisi_barang' => 'Auto fokus lancar dan akurat.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/lens.jpg'],
                'nama_barang' => 'Lensa Sigma 16mm f/1.4 DC DN For Sony',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lensa',
                'deskripsi_barang' => 'Lensa wide-angle dengan bukaan besar, sangat ideal untuk foto pemandangan maupun vlogging low-light.',
                'stok' => 3,
                'harga_perhari' => 75000.00,
                'harga_perjam' => 10000.00,
                'catatan_kondisi_barang' => 'Mulus, kelengkapan termasuk lens hood.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/kamera_accessories.jpg'],
                'nama_barang' => 'Tripod Manfrotto BeFree Advanced',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Aksesoris Kamera',
                'deskripsi_barang' => 'Tripod travel kokoh berbahan aluminium ringan, mampu menahan beban setup kamera hingga 8 kg.',
                'stok' => 5,
                'harga_perhari' => 45000.00,
                'harga_perjam' => 5000.00,
                'catatan_kondisi_barang' => 'Semua kunci kaki dan ballhead berfungsi normal.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/kamera_accessories.jpg'],
                'nama_barang' => 'Gimbal DJI Ronin-SC',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Aksesoris Kamera',
                'deskripsi_barang' => 'Stabilizer kamera 3-axis yang ringan dan portabel untuk menghasilkan rekaman video sinematik.',
                'stok' => 3,
                'harga_perhari' => 100000.00,
                'harga_perjam' => 15000.00,
                'catatan_kondisi_barang' => 'Motor kuat, kalibrasi balance normal, sudah termasuk hardcase.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/kamera_accessories.jpg'],
                'nama_barang' => 'Godox SL60W LED Video Light',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lighting',
                'deskripsi_barang' => 'Lampu continuous studio dengan daya 60W warna daylight (5600K) konstan untuk pencahayaan video.',
                'stok' => 4,
                'harga_perhari' => 60000.00,
                'harga_perjam' => 10000.00,
                'catatan_kondisi_barang' => 'Disewakan paket lengkap dengan light stand dan standard reflector.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/kamera_accessories.jpg'],
                'nama_barang' => 'Godox TT600 Speedlite Flash',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Lighting',
                'deskripsi_barang' => 'Flash eksternal kamera universal manual dengan transmisi wireless gila 2.4G internal.',
                'stok' => 6,
                'harga_perhari' => 30000.00,
                'harga_perjam' => 5000.00,
                'catatan_kondisi_barang' => 'Mulus, bonus kaki bebek/mini stand. Tidak termasuk baterai AA.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/kamera_accessories.jpg'],
                'nama_barang' => 'Rode Wireless GO II Dual Channel',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Audio',
                'deskripsi_barang' => 'Sistem mikrofon nirkabel ultra-ringkas yang terdiri dari dua transmitter (dua orang sekaligus) dan satu receiver.',
                'stok' => 4,
                'harga_perhari' => 120000.00,
                'harga_perjam' => 15000.00,
                'catatan_kondisi_barang' => 'Audio jernih, kabel konektor ke kamera lengkap.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/kamera_accessories.jpg'],
                'nama_barang' => 'Microphone Shotgun Rode VideoMic Pro+',
                'kategori_barang' => 'Kamera',
                'subkategori_barang' => 'Audio',
                'deskripsi_barang' => 'Microphone shotgun premium on-camera dengan sistem power otomatis dan penangkap audio directional terfokus.',
                'stok' => 3,
                'harga_perhari' => 65000.00,
                'harga_perjam' => 10000.00,
                'catatan_kondisi_barang' => 'Busa pelindung angin (windshield) bersih dan tidak robek.',
                'status_barang' => 'Tersedia',
            ],

            // KATEGORI: ALAT CAMPING (15 Barang)
            [
                'gambar_barang' => ['images/tent.jpg'],
                'nama_barang' => 'Tenda Eiger Shadow 4P',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Tenda',
                'deskripsi_barang' => 'Tenda camping premium kapasitas 4 orang dengan sistem double layer tahan badai hujan.',
                'stok' => 8,
                'harga_perhari' => 70000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Pasak, tali, dan frame lengkap, kain tidak ada yang bocor.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/tent.jpg'],
                'nama_barang' => 'Tenda Consina Magnum 4',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Tenda',
                'deskripsi_barang' => 'Tenda dome terlaris dengan teras depan yang luas untuk memasak atau menaruh barang bawaan.',
                'stok' => 10,
                'harga_perhari' => 55000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Kondisi bersih pasca dicuci, frame elastis aman.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/tent.jpg'],
                'nama_barang' => 'Tenda Naturehike Mongar 2P Ultra Light',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Tenda',
                'deskripsi_barang' => 'Tenda kapasitas 2 orang berbahan Nylon 20D silikon super ringan, cocok untuk pendakian ultralight.',
                'stok' => 4,
                'harga_perhari' => 80000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Termasuk footprint original, kondisi mulus.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Sleeping Bag Polar Bulu Eiger',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Tidur',
                'deskripsi_barang' => 'Kantung tidur tebal dengan lapisan dalam bulu polar penahan hawa dingin ekstrem gunung.',
                'stok' => 15,
                'harga_perhari' => 15000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Sudah dicuci bersih dan wangi laundry.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Kasur Angin Naturehike Single',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Tidur',
                'deskripsi_barang' => 'Kasur tiup portabel tebal untuk kenyamanan tidur maksimal di dalam tenda.',
                'stok' => 6,
                'harga_perhari' => 25000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Bebas bocor halus, termasuk pompa manual.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Matras Alumunium Foil Double',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Tidur',
                'deskripsi_barang' => 'Matras pelapis lantai tenda dengan lapisan foil peredam dingin dari permukaan tanah.',
                'stok' => 20,
                'harga_perhari' => 5000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Bersih, tidak robek.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Kompor Camping Portable Kotak',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Memasak',
                'deskripsi_barang' => 'Kompor mini portable menggunakan bahan bakar gas kaleng (hi-cook), praktis dan ringan.',
                'stok' => 12,
                'harga_perhari' => 10000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Pemantik api berfungsi normal, tekanan gas stabil.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Kompor Windproof Gunung (Mawar)',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Memasak',
                'deskripsi_barang' => 'Kompor camping dengan pelindung angin terintegrasi berbentuk kelopak mawar agar api tidak mudah mati.',
                'stok' => 8,
                'harga_perhari' => 15000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Kaki penopang kokoh, pemantik normal.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Cooking Set Nesting DS-308',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Peralatan Memasak',
                'deskripsi_barang' => 'Paket alat masak camping bahan anodized aluminium anti lengket terdiri dari panci, wajan, dan teko kecil.',
                'stok' => 10,
                'harga_perhari' => 15000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Lengkap beserta tas jaringnya, kondisi bersih tanpa gosong berat.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Senter SWAT LED Super Terang',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Penerangan',
                'deskripsi_barang' => 'Senter genggam taktis berdaya sorot jauh dengan fitur zoom in/out dan baterai rechargeable.',
                'stok' => 12,
                'harga_perhari' => 8000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Termasuk kabel charger dan baterai full.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Lentera Tenda Camping Retro LED',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Penerangan',
                'deskripsi_barang' => 'Lampu lentera gantung untuk di dalam tenda dengan cahaya hangat (warm white) yang nyaman dimata.',
                'stok' => 10,
                'harga_perhari' => 10000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Kondisi mulus, fitur dimmer terang-redup aktif.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Headlamp Petzl Tikka',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Penerangan',
                'deskripsi_barang' => 'Senter kepala (headlamp) standar pendakian profesional yang ringan dengan sebaran cahaya merata.',
                'stok' => 6,
                'harga_perhari' => 25000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Karet kepala kencang, tidak melar.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Power Station Portable Anker 256Wh',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Power',
                'deskripsi_barang' => 'Powerbank raksasa (generator mini) dengan colokan AC 220V biasa untuk mengecas laptop atau setup lampu di hutan.',
                'stok' => 2,
                'harga_perhari' => 150000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Kapasitas sel baterai prima, disewakan dalam keadaan baterai 100%.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Solar Panel Charger Portable 21W',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Power',
                'deskripsi_barang' => 'Panel surya lipat yang bisa digantung di ransel untuk mengisi daya hp memanfaatkan sinar matahari selama tracking.',
                'stok' => 3,
                'harga_perhari' => 30000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Port USB output berfungsi stabil di bawah terik matahari.',
                'status_barang' => 'Tersedia',
            ],
            [
                'gambar_barang' => ['images/camping_gear.jpg'],
                'nama_barang' => 'Powerbank Robot 20000mAh Dual Port',
                'kategori_barang' => 'Alat Camping',
                'subkategori_barang' => 'Power',
                'deskripsi_barang' => 'Powerbank standar kapasitas besar pendukung cadangan daya handphone selama berkemah.',
                'stok' => 10,
                'harga_perhari' => 10000.00,
                'harga_perjam' => 0.00,
                'catatan_kondisi_barang' => 'Body ada goresan tipis, sirkuit aman tidak kembung.',
                'status_barang' => 'Tersedia',
            ],
        ];

        // Memasukkan total ke-30 data spesifik ke database
        foreach ($barangs as $barang) {
            Barang::create($barang);
        }
    }
}